name: Push on develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file ./projeto-gcm-server/pom.xml
      
    - name: Config and push Git tag
      run: |
        TAG_NAME="build-${{ github.run_number }}"
        git tag $TAG_NAME
        git push --tags
   
